package com.uleehub.webservice.soap.alipay;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-07-05T13:21:24.458+08:00
 * Generated source version: 2.7.1
 * 
 */
@WebServiceClient(name = "AliPayService", 
                  wsdlLocation = "http://localhost:8080/UleehubPayWs/cxf/uleepay/aliPayService?wsdl",
                  targetNamespace = "http://uleehub.pay.com") 
public class AliPayService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://uleehub.pay.com", "AliPayService");
    public final static QName AliPayServiceImplPort = new QName("http://uleehub.pay.com", "AliPayServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/UleehubPayWs/cxf/uleepay/aliPayService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AliPayService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/UleehubPayWs/cxf/uleepay/aliPayService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AliPayService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AliPayService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AliPayService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AliPayService
     */
    @WebEndpoint(name = "AliPayServiceImplPort")
    public AliPayService getAliPayServiceImplPort() {
        return super.getPort(AliPayServiceImplPort, AliPayService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AliPayService
     */
    @WebEndpoint(name = "AliPayServiceImplPort")
    public AliPayService getAliPayServiceImplPort(WebServiceFeature... features) {
        return super.getPort(AliPayServiceImplPort, AliPayService.class, features);
    }

}
