package com.uleehub.webservice.soap.alipay;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-07-05T13:21:24.381+08:00
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://uleehub.pay.com", name = "AliPayService")
@XmlSeeAlso({ObjectFactory.class})
public interface AliPayService {

    @RequestWrapper(localName = "pay", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.alipay.Pay")
    @ResponseWrapper(localName = "payResponse", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.alipay.PayResponse")
    @WebMethod(operationName = "pay")
    public Response<com.uleehub.webservice.soap.alipay.PayResponse> payAsync(
        @WebParam(name = "out_trade_no", targetNamespace = "")
        java.lang.String outTradeNo,
        @WebParam(name = "subject", targetNamespace = "")
        java.lang.String subject,
        @WebParam(name = "subject_num", targetNamespace = "")
        java.lang.String subjectNum,
        @WebParam(name = "total_fee", targetNamespace = "")
        java.lang.String totalFee,
        @WebParam(name = "body", targetNamespace = "")
        java.lang.String body,
        @WebParam(name = "show_url", targetNamespace = "")
        java.lang.String showUrl,
        @WebParam(name = "exter_invoke_ip", targetNamespace = "")
        java.lang.String exterInvokeIp,
        @WebParam(name = "purchaser_id", targetNamespace = "")
        java.lang.String purchaserId,
        @WebParam(name = "purchaser_name", targetNamespace = "")
        java.lang.String purchaserName
    );

    @RequestWrapper(localName = "pay", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.alipay.Pay")
    @ResponseWrapper(localName = "payResponse", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.alipay.PayResponse")
    @WebMethod(operationName = "pay")
    public Future<?> payAsync(
        @WebParam(name = "out_trade_no", targetNamespace = "")
        java.lang.String outTradeNo,
        @WebParam(name = "subject", targetNamespace = "")
        java.lang.String subject,
        @WebParam(name = "subject_num", targetNamespace = "")
        java.lang.String subjectNum,
        @WebParam(name = "total_fee", targetNamespace = "")
        java.lang.String totalFee,
        @WebParam(name = "body", targetNamespace = "")
        java.lang.String body,
        @WebParam(name = "show_url", targetNamespace = "")
        java.lang.String showUrl,
        @WebParam(name = "exter_invoke_ip", targetNamespace = "")
        java.lang.String exterInvokeIp,
        @WebParam(name = "purchaser_id", targetNamespace = "")
        java.lang.String purchaserId,
        @WebParam(name = "purchaser_name", targetNamespace = "")
        java.lang.String purchaserName,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.uleehub.webservice.soap.alipay.PayResponse> asyncHandler
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "pay", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.alipay.Pay")
    @WebMethod
    @ResponseWrapper(localName = "payResponse", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.alipay.PayResponse")
    public com.uleehub.webservice.soap.alipay.GetSHtmlTextResult pay(
        @WebParam(name = "out_trade_no", targetNamespace = "")
        java.lang.String outTradeNo,
        @WebParam(name = "subject", targetNamespace = "")
        java.lang.String subject,
        @WebParam(name = "subject_num", targetNamespace = "")
        java.lang.String subjectNum,
        @WebParam(name = "total_fee", targetNamespace = "")
        java.lang.String totalFee,
        @WebParam(name = "body", targetNamespace = "")
        java.lang.String body,
        @WebParam(name = "show_url", targetNamespace = "")
        java.lang.String showUrl,
        @WebParam(name = "exter_invoke_ip", targetNamespace = "")
        java.lang.String exterInvokeIp,
        @WebParam(name = "purchaser_id", targetNamespace = "")
        java.lang.String purchaserId,
        @WebParam(name = "purchaser_name", targetNamespace = "")
        java.lang.String purchaserName
    );

    @RequestWrapper(localName = "payByDTO", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.alipay.PayByDTO")
    @ResponseWrapper(localName = "payByDTOResponse", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.alipay.PayByDTOResponse")
    @WebMethod(operationName = "payByDTO")
    public Response<com.uleehub.webservice.soap.alipay.PayByDTOResponse> payByDTOAsync(
        @WebParam(name = "tradeInfo", targetNamespace = "")
        com.uleehub.webservice.soap.alipay.TradeInfo tradeInfo
    );

    @RequestWrapper(localName = "payByDTO", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.alipay.PayByDTO")
    @ResponseWrapper(localName = "payByDTOResponse", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.alipay.PayByDTOResponse")
    @WebMethod(operationName = "payByDTO")
    public Future<?> payByDTOAsync(
        @WebParam(name = "tradeInfo", targetNamespace = "")
        com.uleehub.webservice.soap.alipay.TradeInfo tradeInfo,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.uleehub.webservice.soap.alipay.PayByDTOResponse> asyncHandler
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "payByDTO", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.alipay.PayByDTO")
    @WebMethod
    @ResponseWrapper(localName = "payByDTOResponse", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.alipay.PayByDTOResponse")
    public com.uleehub.webservice.soap.alipay.GetSHtmlTextResult payByDTO(
        @WebParam(name = "tradeInfo", targetNamespace = "")
        com.uleehub.webservice.soap.alipay.TradeInfo tradeInfo
    );

    @RequestWrapper(localName = "queryPayStatus", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.alipay.QueryPayStatus")
    @ResponseWrapper(localName = "queryPayStatusResponse", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.alipay.QueryPayStatusResponse")
    @WebMethod(operationName = "queryPayStatus")
    public Response<com.uleehub.webservice.soap.alipay.QueryPayStatusResponse> queryPayStatusAsync(
        @WebParam(name = "out_trade_no", targetNamespace = "")
        java.lang.String outTradeNo
    );

    @RequestWrapper(localName = "queryPayStatus", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.alipay.QueryPayStatus")
    @ResponseWrapper(localName = "queryPayStatusResponse", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.alipay.QueryPayStatusResponse")
    @WebMethod(operationName = "queryPayStatus")
    public Future<?> queryPayStatusAsync(
        @WebParam(name = "out_trade_no", targetNamespace = "")
        java.lang.String outTradeNo,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.uleehub.webservice.soap.alipay.QueryPayStatusResponse> asyncHandler
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryPayStatus", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.alipay.QueryPayStatus")
    @WebMethod
    @ResponseWrapper(localName = "queryPayStatusResponse", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.alipay.QueryPayStatusResponse")
    public com.uleehub.webservice.soap.alipay.GetStatusResult queryPayStatus(
        @WebParam(name = "out_trade_no", targetNamespace = "")
        java.lang.String outTradeNo
    );
}
