package com.uleehub.webservice.soap.icbcpay;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-07-05T15:27:52.416+08:00
 * Generated source version: 2.7.1
 * 
 */
@WebServiceClient(name = "IcbcB2cPayService", 
                  wsdlLocation = "http://localhost:8080/UleehubPayWs/cxf/uleepay/icbcB2cPayService?wsdl",
                  targetNamespace = "http://uleehub.pay.com") 
public class IcbcB2CPayService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://uleehub.pay.com", "IcbcB2cPayService");
    public final static QName IcbcB2CPayServiceImplPort = new QName("http://uleehub.pay.com", "IcbcB2cPayServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/UleehubPayWs/cxf/uleepay/icbcB2cPayService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IcbcB2CPayService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/UleehubPayWs/cxf/uleepay/icbcB2cPayService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IcbcB2CPayService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IcbcB2CPayService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IcbcB2CPayService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns IcbcB2CPayService
     */
    @WebEndpoint(name = "IcbcB2cPayServiceImplPort")
    public IcbcB2CPayService getIcbcB2CPayServiceImplPort() {
        return super.getPort(IcbcB2CPayServiceImplPort, IcbcB2CPayService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IcbcB2CPayService
     */
    @WebEndpoint(name = "IcbcB2cPayServiceImplPort")
    public IcbcB2CPayService getIcbcB2CPayServiceImplPort(WebServiceFeature... features) {
        return super.getPort(IcbcB2CPayServiceImplPort, IcbcB2CPayService.class, features);
    }

}
