package com.uleehub.webservice.soap.icbcpay;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-07-05T15:27:52.337+08:00
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://uleehub.pay.com", name = "IcbcB2cPayService")
@XmlSeeAlso({ObjectFactory.class})
public interface IcbcB2CPayService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "pay", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.icbcpay.Pay")
    @WebMethod
    @ResponseWrapper(localName = "payResponse", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.icbcpay.PayResponse")
    public com.uleehub.webservice.soap.icbcpay.GetSHtmlTextResult pay(
        @WebParam(name = "out_trade_no", targetNamespace = "")
        java.lang.String outTradeNo,
        @WebParam(name = "subject", targetNamespace = "")
        java.lang.String subject,
        @WebParam(name = "subject_num", targetNamespace = "")
        java.lang.String subjectNum,
        @WebParam(name = "total_fee", targetNamespace = "")
        java.lang.String totalFee,
        @WebParam(name = "body", targetNamespace = "")
        java.lang.String body,
        @WebParam(name = "show_url", targetNamespace = "")
        java.lang.String showUrl,
        @WebParam(name = "exter_invoke_ip", targetNamespace = "")
        java.lang.String exterInvokeIp,
        @WebParam(name = "purchaser_id", targetNamespace = "")
        java.lang.String purchaserId,
        @WebParam(name = "purchaser_name", targetNamespace = "")
        java.lang.String purchaserName
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "payByDTO", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.icbcpay.PayByDTO")
    @WebMethod
    @ResponseWrapper(localName = "payByDTOResponse", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.icbcpay.PayByDTOResponse")
    public com.uleehub.webservice.soap.icbcpay.GetSHtmlTextResult payByDTO(
        @WebParam(name = "tradeInfo", targetNamespace = "")
        com.uleehub.webservice.soap.icbcpay.TradeInfo tradeInfo
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryPayStatus", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.icbcpay.QueryPayStatus")
    @WebMethod
    @ResponseWrapper(localName = "queryPayStatusResponse", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.icbcpay.QueryPayStatusResponse")
    public com.uleehub.webservice.soap.icbcpay.GetStatusResult queryPayStatus(
        @WebParam(name = "out_trade_no", targetNamespace = "")
        java.lang.String outTradeNo
    );
}
