
package com.uleehub.webservice.soap.icbcpay;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import javax.xml.namespace.QName;

import org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor;
import org.apache.cxf.endpoint.Client;
import org.apache.cxf.endpoint.Endpoint;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.transport.http.HTTPConduit;
import org.apache.cxf.transports.http.configuration.HTTPClientPolicy;
import org.apache.cxf.ws.security.wss4j.WSS4JOutInterceptor;
import org.apache.ws.security.WSConstants;
import org.apache.ws.security.handler.WSHandlerConstants;

import com.uleehub.webservice.soap.security.WsClientAuthHandler;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-07-05T15:27:52.061+08:00
 * Generated source version: 2.7.1
 * 
 */
public final class TIcbcB2CPayServiceIT {

    private static final QName SERVICE_NAME = new QName("http://uleehub.pay.com", "IcbcB2cPayService");

    private TIcbcB2CPayServiceIT() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IcbcB2CPayService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IcbcB2CPayService_Service ss = new IcbcB2CPayService_Service(wsdlURL, SERVICE_NAME);
        IcbcB2CPayService port = ss.getIcbcB2CPayServiceImplPort();  
        
        Client client = ClientProxy.getClient(port);
        Endpoint endpoint = client.getEndpoint();
        Map<String,Object> props = new HashMap<String,Object>();  
        props.put(WSHandlerConstants.ACTION, WSHandlerConstants.USERNAME_TOKEN);  
        props.put(WSHandlerConstants.USER, "admin");  
        props.put(WSHandlerConstants.PASSWORD_TYPE, WSConstants.PW_TEXT); 
     // 指定在调用远程ws之前触发的回调函数WsClientAuthHandler，其实类似于一个拦截器
        props.put(WSHandlerConstants.PW_CALLBACK_CLASS, WsClientAuthHandler.class.getName());  
        SAAJOutInterceptor saaJOutInterceptor = new SAAJOutInterceptor();
        WSS4JOutInterceptor wss4JOutInterceptor = new WSS4JOutInterceptor(props);
        ArrayList list = new ArrayList();  
        // 添加cxf安全验证拦截器，必须  
        list.add(saaJOutInterceptor);  
        list.add(wss4JOutInterceptor);
        endpoint.getOutInterceptors().addAll(list);
          
        HTTPConduit conduit = (HTTPConduit) client.getConduit();  
        HTTPClientPolicy policy = new HTTPClientPolicy();  
        policy.setConnectionTimeout(600 * 1000);  
        policy.setReceiveTimeout(600 * 1000);  
        conduit.setClient(policy);
        
        {
        System.out.println("Invoking pay...");
        java.lang.String _pay_outTradeNo = "20140630222620";
        java.lang.String _pay_subject = "澳洲十日游";
        java.lang.String _pay_subjectNum = "1";
        java.lang.String _pay_totalFee = "8000";
        java.lang.String _pay_body = "澳洲十日游";
        java.lang.String _pay_showUrl = "http://aozou/show/detail/1";
        java.lang.String _pay_exterInvokeIp = "192.168.1.1";
        java.lang.String _pay_purchaserId = "mtwu";
        java.lang.String _pay_purchaserName = "wujian";
        com.uleehub.webservice.soap.icbcpay.GetSHtmlTextResult _pay__return = port.pay(_pay_outTradeNo, _pay_subject, _pay_subjectNum, _pay_totalFee, _pay_body, _pay_showUrl, _pay_exterInvokeIp, _pay_purchaserId, _pay_purchaserName);
        System.out.println("refund.code=" + _pay__return.code);
        System.out.println("refund.message=" + _pay__return.message);
        System.out.println("refund.result=" + _pay__return.getSHtmlText());


        }
        /*
        {
        System.out.println("Invoking payByDTO...");
        com.uleehub.webservice.soap.icbcpay.TradeInfo _payByDTO_tradeInfo = null;
        com.uleehub.webservice.soap.icbcpay.GetSHtmlTextResult _payByDTO__return = port.payByDTO(_payByDTO_tradeInfo);
        System.out.println("payByDTO.result=" + _payByDTO__return);


        }
        {
        System.out.println("Invoking queryPayStatus...");
        java.lang.String _queryPayStatus_outTradeNo = "";
        com.uleehub.webservice.soap.icbcpay.GetStatusResult _queryPayStatus__return = port.queryPayStatus(_queryPayStatus_outTradeNo);
        System.out.println("queryPayStatus.result=" + _queryPayStatus__return);


        }
		*/
        System.exit(0);
    }

}
