package com.uleehub.webservice.soap.alirefund;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-07-05T15:27:04.580+08:00
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://uleehub.pay.com", name = "AliRefundService")
@XmlSeeAlso({ObjectFactory.class})
public interface AliRefundService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "refund", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.alirefund.Refund")
    @WebMethod
    @ResponseWrapper(localName = "refundResponse", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.alirefund.RefundResponse")
    public com.uleehub.webservice.soap.alirefund.GetSHtmlTextResult refund(
        @WebParam(name = "batch_no", targetNamespace = "")
        java.lang.String batchNo,
        @WebParam(name = "batch_num", targetNamespace = "")
        java.lang.String batchNum,
        @WebParam(name = "detail_data", targetNamespace = "")
        java.lang.String detailData,
        @WebParam(name = "exter_invoke_ip", targetNamespace = "")
        java.lang.String exterInvokeIp,
        @WebParam(name = "purchaser_id", targetNamespace = "")
        java.lang.String purchaserId,
        @WebParam(name = "purchaser_name", targetNamespace = "")
        java.lang.String purchaserName
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "queryRefundStatus", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.alirefund.QueryRefundStatus")
    @WebMethod
    @ResponseWrapper(localName = "queryRefundStatusResponse", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.alirefund.QueryRefundStatusResponse")
    public com.uleehub.webservice.soap.alirefund.GetStatusResult queryRefundStatus(
        @WebParam(name = "batch_no", targetNamespace = "")
        java.lang.String batchNo
    );
}
