package com.uleehub.webservice.soap.alirefund;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-07-05T15:27:04.640+08:00
 * Generated source version: 2.7.1
 * 
 */
@WebServiceClient(name = "AliRefundService", 
                  wsdlLocation = "http://localhost:8080/UleehubPayWs/cxf/uleepay/aliRefundService?wsdl",
                  targetNamespace = "http://uleehub.pay.com") 
public class AliRefundService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://uleehub.pay.com", "AliRefundService");
    public final static QName AliRefundServiceImplPort = new QName("http://uleehub.pay.com", "AliRefundServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/UleehubPayWs/cxf/uleepay/aliRefundService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AliRefundService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/UleehubPayWs/cxf/uleepay/aliRefundService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AliRefundService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AliRefundService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AliRefundService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AliRefundService
     */
    @WebEndpoint(name = "AliRefundServiceImplPort")
    public AliRefundService getAliRefundServiceImplPort() {
        return super.getPort(AliRefundServiceImplPort, AliRefundService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AliRefundService
     */
    @WebEndpoint(name = "AliRefundServiceImplPort")
    public AliRefundService getAliRefundServiceImplPort(WebServiceFeature... features) {
        return super.getPort(AliRefundServiceImplPort, AliRefundService.class, features);
    }

}
