
package com.uleehub.webservice.soap.alirefund;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import javax.xml.namespace.QName;

import org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor;
import org.apache.cxf.endpoint.Client;
import org.apache.cxf.endpoint.Endpoint;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;
import org.apache.cxf.transport.http.HTTPConduit;
import org.apache.cxf.transports.http.configuration.HTTPClientPolicy;
import org.apache.cxf.ws.security.wss4j.WSS4JOutInterceptor;
import org.apache.ws.security.WSConstants;
import org.apache.ws.security.handler.WSHandlerConstants;

import com.uleehub.webservice.soap.security.WsClientAuthHandler;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-07-05T15:27:04.341+08:00
 * Generated source version: 2.7.1
 * 
 */
public final class TAliRefundServiceIT {

    private static final QName SERVICE_NAME = new QName("http://uleehub.pay.com", "AliRefundService");

    private TAliRefundServiceIT() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AliRefundService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
        JaxWsProxyFactoryBean factoryBean = new JaxWsProxyFactoryBean();
        AliRefundService_Service ss = new AliRefundService_Service(wsdlURL, SERVICE_NAME);
        AliRefundService port = ss.getAliRefundServiceImplPort();  
        
        
        Client client = ClientProxy.getClient(port);
        Endpoint endpoint = client.getEndpoint();
        Map<String,Object> props = new HashMap<String,Object>();  
        props.put(WSHandlerConstants.ACTION, WSHandlerConstants.USERNAME_TOKEN);  
        props.put(WSHandlerConstants.USER, "admin");  
        props.put(WSHandlerConstants.PASSWORD_TYPE, WSConstants.PW_TEXT); 
     // 指定在调用远程ws之前触发的回调函数WsClientAuthHandler，其实类似于一个拦截器
        props.put(WSHandlerConstants.PW_CALLBACK_CLASS, WsClientAuthHandler.class.getName());  
        SAAJOutInterceptor saaJOutInterceptor = new SAAJOutInterceptor();
        WSS4JOutInterceptor wss4JOutInterceptor = new WSS4JOutInterceptor(props);
        ArrayList list = new ArrayList();  
        // 添加cxf安全验证拦截器，必须  
        list.add(saaJOutInterceptor);  
        list.add(wss4JOutInterceptor);
        endpoint.getOutInterceptors().addAll(list);
        
        HTTPConduit conduit = (HTTPConduit) client.getConduit();  
        HTTPClientPolicy policy = new HTTPClientPolicy();  
        policy.setConnectionTimeout(600 * 1000);  
        policy.setReceiveTimeout(600 * 1000);  
        conduit.setClient(policy);
        
        {
        System.out.println("Invoking refund...");
        java.lang.String _refund_batchNo = "201406271729300001";
        java.lang.String _refund_batchNum = "1";
        java.lang.String _refund_detailData = "123456^0.01^协商退款";
        java.lang.String _refund_exterInvokeIp = "192.168.0.1";
        java.lang.String _refund_purchaserId = "mtwu";
        java.lang.String _refund_purchaserName = "wujian";
        com.uleehub.webservice.soap.alirefund.GetSHtmlTextResult _refund__return = port.refund(_refund_batchNo, _refund_batchNum, _refund_detailData, _refund_exterInvokeIp, _refund_purchaserId, _refund_purchaserName);
        System.out.println("refund.code=" + _refund__return.code);
        System.out.println("refund.message=" + _refund__return.message);
        System.out.println("refund.result=" + _refund__return.getSHtmlText());


        }
        /*
        {
        System.out.println("Invoking queryRefundStatus...");
        java.lang.String _queryRefundStatus_batchNo = "";
        com.uleehub.webservice.soap.alirefund.GetStatusResult _queryRefundStatus__return = port.queryRefundStatus(_queryRefundStatus_batchNo);
        System.out.println("queryRefundStatus.result=" + _queryRefundStatus__return);


        }
		*/
        System.exit(0);
    }

}
