package com.uleehub.webservice.soap.icbcpaystatus;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-07-05T17:31:09.374+08:00
 * Generated source version: 2.7.1
 * 
 */
@WebService(targetNamespace = "http://uleehub.pay.com", name = "IcbcB2cPayStatusService")
@XmlSeeAlso({ObjectFactory.class})
public interface IcbcB2CPayStatusService {

    @RequestWrapper(localName = "query", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.icbcpaystatus.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.icbcpaystatus.QueryResponse")
    @WebMethod(operationName = "query")
    public Response<com.uleehub.webservice.soap.icbcpaystatus.QueryResponse> queryAsync(
        @WebParam(name = "out_trade_no", targetNamespace = "")
        java.lang.String outTradeNo
    );

    @RequestWrapper(localName = "query", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.icbcpaystatus.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.icbcpaystatus.QueryResponse")
    @WebMethod(operationName = "query")
    public Future<?> queryAsync(
        @WebParam(name = "out_trade_no", targetNamespace = "")
        java.lang.String outTradeNo,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<com.uleehub.webservice.soap.icbcpaystatus.QueryResponse> asyncHandler
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "query", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.icbcpaystatus.Query")
    @WebMethod
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://uleehub.pay.com", className = "com.uleehub.webservice.soap.icbcpaystatus.QueryResponse")
    public com.uleehub.webservice.soap.icbcpaystatus.GetQueryStatusResult query(
        @WebParam(name = "out_trade_no", targetNamespace = "")
        java.lang.String outTradeNo
    );
}
