
package com.uleehub.webservice.soap.icbcpaystatus;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

import javax.xml.namespace.QName;
import javax.xml.ws.Response;

import org.apache.cxf.binding.soap.saaj.SAAJOutInterceptor;
import org.apache.cxf.endpoint.Client;
import org.apache.cxf.endpoint.Endpoint;
import org.apache.cxf.frontend.ClientProxy;
import org.apache.cxf.transport.http.HTTPConduit;
import org.apache.cxf.transports.http.configuration.HTTPClientPolicy;
import org.apache.cxf.ws.security.wss4j.WSS4JOutInterceptor;
import org.apache.ws.security.WSConstants;
import org.apache.ws.security.handler.WSHandlerConstants;

import com.uleehub.webservice.soap.security.WsClientAuthHandler;

/**
 * This class was generated by Apache CXF 2.7.1
 * 2014-07-05T16:46:01.510+08:00
 * Generated source version: 2.7.1
 * 
 */
public final class TIcbcB2CPayStatusServiceIT {

    private static final QName SERVICE_NAME = new QName("http://uleehub.pay.com", "IcbcB2cPayStatusService");

    private TIcbcB2CPayStatusServiceIT() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IcbcB2CPayStatusService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IcbcB2CPayStatusService_Service ss = new IcbcB2CPayStatusService_Service(wsdlURL, SERVICE_NAME);
        IcbcB2CPayStatusService port = ss.getIcbcB2CPayStatusServiceImplPort();  
        
        Client client = ClientProxy.getClient(port);
        Endpoint endpoint = client.getEndpoint();
          
        Map<String,Object> props = new HashMap<String,Object>();  
        props.put(WSHandlerConstants.ACTION, WSHandlerConstants.USERNAME_TOKEN);  
        props.put(WSHandlerConstants.USER, "admin");  
        props.put(WSHandlerConstants.PASSWORD_TYPE, WSConstants.PW_TEXT); 
     // 指定在调用远程ws之前触发的回调函数WsClientAuthHandler，其实类似于一个拦截器
        props.put(WSHandlerConstants.PW_CALLBACK_CLASS, WsClientAuthHandler.class.getName());  
        SAAJOutInterceptor saaJOutInterceptor = new SAAJOutInterceptor();
        WSS4JOutInterceptor wss4JOutInterceptor = new WSS4JOutInterceptor(props);
        ArrayList list = new ArrayList();  
        // 添加cxf安全验证拦截器，必须  
        list.add(saaJOutInterceptor);  
        list.add(wss4JOutInterceptor);
        endpoint.getOutInterceptors().addAll(list);
          
        HTTPConduit conduit = (HTTPConduit) client.getConduit();  
        HTTPClientPolicy policy = new HTTPClientPolicy();  
        policy.setConnectionTimeout(600 * 1000);  
        policy.setReceiveTimeout(600 * 1000);  
        conduit.setClient(policy);
        
        {
        System.out.println("Invoking query...");
        java.lang.String _query_outTradeNo = "20140630222620";
        //com.uleehub.webservice.soap.icbcpaystatus.GetQueryStatusResult _query__return = port.query(_query_outTradeNo);
        Response<com.uleehub.webservice.soap.icbcpaystatus.QueryResponse> _queryAsync__return = port.queryAsync(_query_outTradeNo);
        
        while (!_queryAsync__return.isDone()) {
			System.out.println("is not done");
			Thread.sleep(1000);
		}
        com.uleehub.webservice.soap.icbcpaystatus.GetQueryStatusResult _query__return = _queryAsync__return.get().getReturn();
        
        System.out.println("query.code=" + _query__return.getCode());
        System.out.println("query.message=" + _query__return.getMessage());
        System.out.println("query.status=" + _query__return.getStatus());
        System.out.println("query.bankInfo=" + _query__return.getBankInfo());


        }

        System.exit(0);
    }

}
